import type { OperatorSnapshot } from "./types";

export const SNAPSHOT: OperatorSnapshot = {
  generatedAt: "2026-09-01T21:15:00Z",
  agent: "Grok (Administrator)",
  master: {
    sha: "83893ba9a287b171342761fcce5fe80303845b27",
    short: "83893ba",
    message: "docs(ops): add reconciliation control-plane navigation index",
    sheVersion: "0.14.0",
    publishOnMaster: false,
  },
  counts: { openIssues: 96, openPrs: 50, workflowRunsSampled: 75205 },
  bands: [
    {
      id: "P0",
      title: "Unblock CI / Ops / Resilience",
      blurb: "Must stay green. Dual gates only. No force-push to master.",
      items: [
        {
          id: "gate",
          title: "Master functional gate",
          status: "live",
          action: "repo_gate + termux_smoke remain the only merge gates",
          refs: ["#175", "docs/ARCHW1Z-GATE.md"],
        },
        {
          id: "ledger",
          title: "PR production ledger",
          status: "fail",
          action: "Fails on issue_comment for non-PR issues — skip 404, do not fail the job",
          refs: ["#268", "#337", "pr-production-ledger.yml"],
        },
        {
          id: "she-p014",
          title: "SHE P0.14 publication planner",
          status: "hold",
          action: "she/publish.py not on master. #411 stale vs 83893ba — rebase extract",
          refs: ["#294", "#401", "#411"],
        },
        {
          id: "dirty",
          title: "Dirty mega PRs",
          status: "dirty",
          action: "Do not wholesale merge. Extract only.",
          refs: ["#263", "#390", "#402", "#403"],
        },
      ],
    },
    {
      id: "P1",
      title: "Security / Hygiene",
      blurb: "Sentinel extracts over 49-file megas. GitLab non-blocking.",
      items: [
        {
          id: "sentinel-vault",
          title: "Symlink vault / chmod / cmd_export",
          status: "extract",
          action: "Prefer #414 / #419 / #404 over dirty #402",
          refs: ["#414", "#419", "#404", "#92"],
        },
        {
          id: "dependabot",
          title: "Dependabot / security observe-only",
          status: "hold",
          action: "SHE treats dependabot as observe-only. No auto-promote.",
          refs: ["#202", "she/promote.py"],
        },
      ],
    },
    {
      id: "P2",
      title: "Providers / Manus / Routing",
      blurb: "Current product focus. Parked until operator upload of the 22 Aug archive.",
      items: [
        {
          id: "manus",
          title: "#265 Providers RE + Manus replay export",
          status: "parked",
          action: "Drive .manustask unchanged since 2026-08-22 (221 MB)",
          refs: ["#265", "#307", "#308"],
        },
        {
          id: "ox",
          title: "OX-Alpha DeepSeek canary",
          status: "hold",
          action: "Evidence-first. Drafts #386 / #373 stay off master until dual-gate green",
          refs: ["#408", "#409", "#386"],
        },
        {
          id: "hub",
          title: "LLM API Hub (TER-71)",
          status: "extract",
          action: "PR #48 targets master-staging — keep off the master gate",
          refs: ["#48", "TER-71"],
        },
      ],
    },
    {
      id: "P3",
      title: "Comms / Teams / Docs / ML",
      blurb: "Keep ML lineage SHA-bound. Attribution issues stay registry work.",
      items: [
        {
          id: "a2a",
          title: "Agent2Agent / MCP Agent Mail",
          status: "hold",
          action: "Proposal open. Do not comment-loop #143",
          refs: ["#117", "#143"],
        },
        {
          id: "ml",
          title: "ML pipelines + lineage",
          status: "live",
          action: "Land SHA-bound lineage, eval harness, and provider attribution registry",
          refs: ["#343", "#342", "#359"],
        },
        {
          id: "notation",
          title: "Notation sets / Linguist",
          status: "extract",
          action: "Jules #390 is a minesweeper mega — extract cards only",
          refs: ["#320", "#390", "#418"],
        },
      ],
    },
  ],
  prs: [
    {
      number: 411,
      title: "feat(she): P0.14 publication planner (rebased)",
      head: "0d96c03",
      base: "9cfbcb37",
      files: 4,
      mergeable: "unstable",
      lane: "candidate",
      notes: "Stale vs current master 83893ba. Dual-gate slice. Rebase, do not force.",
    },
    {
      number: 401,
      title: "feat(she): P0.14 publication planner stacked on P0.13",
      head: "8e0aeb0",
      base: "8e9839f",
      files: 4,
      mergeable: "unstable",
      lane: "superseded",
      notes: "Superseded by #411 then by current-master extract.",
    },
    {
      number: 414,
      title: "Sentinel: prevent symlink traversal in token vault",
      head: "52d8503",
      base: "61f1e73",
      files: 2,
      mergeable: "unstable",
      lane: "extract",
      notes: "2-file security extract. Rebase after SHE land.",
    },
    {
      number: 419,
      title: "Sentinel: symlink safety on cmd_export",
      head: "6f5eb3f",
      base: "165a451",
      files: 2,
      mergeable: "unstable",
      lane: "extract",
      notes: "2-file extract. Hold until dual-gate re-run on current master.",
    },
    {
      number: 410,
      title: "fix(she): enforce verification contract matching",
      head: "73d86e9",
      base: "9cfbcb37",
      files: 1,
      mergeable: "unstable",
      lane: "extract",
      notes: "Reclassified — may delete landed ledger. Do not merge as-is.",
    },
    {
      number: 390,
      title: "docs: notation sets mega",
      head: "1ddad1e",
      base: "ae18aed",
      files: 0,
      mergeable: "dirty",
      lane: "dirty",
      notes: "Minesweeper. 100s of commits + comment storm. Ack-pending only.",
    },
    {
      number: 48,
      title: "feat(llm-api-hub): OpenAI hub + ADE/kai9000 split",
      head: "7839eeb",
      base: "master-staging",
      files: 0,
      mergeable: "unknown",
      lane: "staging",
      notes: "Off the master gate. TER-71.",
    },
    {
      number: 6,
      title: "fix(TER-9): vibe dispatch wholesale",
      head: "8483f33",
      base: "master-staging",
      files: 0,
      mergeable: "unknown",
      lane: "staging",
      notes: "NO-GO wholesale — extract only per AGENTS.md.",
    },
  ],
  actions: [
    {
      name: "Production Reconciliation Engine",
      conclusion: "success",
      event: "schedule",
      note: "First scheduled run on 83893ba succeeded.",
    },
    {
      name: "Context Relationship + Lead/Lag Audit",
      conclusion: "success",
      event: "workflow_run",
      note: "Healthy; duplicate runs cancel as designed.",
    },
    {
      name: "Peer review orchestrator",
      conclusion: "success",
      event: "issue_comment",
      note: "Green on current HEAD.",
    },
    {
      name: "PR production ledger",
      conclusion: "failure",
      event: "issue_comment",
      note: "Non-PR issue comments 404 pulls.get. Fix skip path.",
    },
    {
      name: "DeepSeek CI / Gemini Dispatch / Jules auto",
      conclusion: "skipped",
      event: "issue_comment",
      note: "Skip-reason expected on non-matching events / quota.",
    },
    {
      name: "Audit Cycle — Single PR Feed-Forward",
      conclusion: "success",
      event: "issue_comment",
      note: "Green.",
    },
  ],
  ml: [
    {
      id: "lineage",
      name: "Experiment lineage",
      state: "hold",
      shaBound: true,
      live: false,
      note: "#343 cycle/run/attempt provenance — land as observer-only first",
    },
    {
      id: "eval",
      name: "Eval harness / leaderboards",
      state: "hold",
      shaBound: true,
      live: false,
      note: "#342 evaluations stay SHA-bound; no live model calls in gate",
    },
    {
      id: "she-learn",
      name: "SHE learn + evolve",
      state: "live",
      shaBound: true,
      live: false,
      note: "P0.8/P0.9 planners on master. Live flags unused.",
    },
    {
      id: "publish",
      name: "SHE publish + receipt",
      state: "hold",
      shaBound: true,
      live: false,
      note: "P0.14/P0.15 extract onto 83893ba",
    },
    {
      id: "attribution",
      name: "Provider attribution registry",
      state: "extract",
      shaBound: true,
      live: false,
      note: "Providence issues #357–#369 as data, not 11 copy-paste PRs",
    },
  ],
  swarm: [
    {
      name: "Grok",
      role: "Administrator / OPERATOR",
      status: "live",
      note: "This cycle. Matrix + ledger + SHE extract + console.",
    },
    {
      name: "Jules",
      role: "Sentinel / Linguist / Bolt",
      status: "hold",
      note: "Many stale-base extracts. Continue-only. No new spawn storm.",
    },
    {
      name: "CodeRabbit",
      role: "Reviewer",
      status: "skip",
      note: "OSS skip / rate-limit = ack_pending, not real_review.",
    },
    {
      name: "Devin",
      role: "Builder (credit)",
      status: "parked",
      note: "Trial expired. Linear still delegates TER-71.",
    },
    {
      name: "Manus",
      role: "Export / RECON",
      status: "parked",
      note: "#265 parked pending operator archive upload.",
    },
    {
      name: "Qodo / Copilot",
      role: "Review",
      status: "skip",
      note: "Non-gate. Request after green dual-gate PR exists.",
    },
  ],
  hardRules: [
    "No force-push to master",
    "Small green rebased PRs only",
    "Merges need repo_gate + termux_smoke",
    "Reject Class 3/4 artifacts",
    "GitLab is non-blocking",
    "Vercel / CodeRabbit / Devin / Qodo are not real_review",
    "Dirty / minesweeper PRs: extract, never wholesale",
    "SHE live flags stay off (observe-only planners)",
  ],
  next: [
    "Fix PR production ledger skip path for non-PR issue comments",
    "Rebase SHE P0.14 publish planner onto 83893ba",
    "Stack P0.15 receipt/ack planner as the next small SHE slice",
    "Land SHA-bound ML lineage + attribution registry (keep pipelines)",
    "Hold #411/#401/#414/#419 until mergeable_state is clean",
    "Do not comment-loop #390",
  ],
};
