#!/usr/bin/env python3
"""Apply the arch-017 refactor to dispatch_task.py."""
import json
from pathlib import Path

HOME = Path.home()
DT = HOME / 'workspace/llm_map/dispatch_task.py'
src = DT.read_text()

# 1. Add target_type handling in run_task
# Find the force-copy block and make it conditional on target_type
old = """        # Force-copy the live source to workspace before each run
    source_file = HOME / source
    workspace_file = WORKSPACE / source_file.name
    if source_file.exists():
        shutil.copy2(source_file, workspace_file)
        log(f'Force-copied {source} → workspace')"""

new = """        # Force-copy based on target_type
    target_type = task.get('target_type', 'source')
    if target_type == 'source':
        source_file = HOME / source
        workspace_file = WORKSPACE / source_file.name
        if source_file.exists() and source_file.is_file():
            shutil.copy2(source_file, workspace_file)
            log(f'Force-copied {source} → workspace')
        else:
            log(f'⚠️ Source file not found: {source}')
    else:
        # Output task – create empty target in workspace
        workspace_file = WORKSPACE / Path(source).name
        workspace_file.write_text('# New file – generated by ArchWiz\\n')
        log(f'Created empty output target: {workspace_file.name}')"""

src = src.replace(old, new)

# 2. After the orchestrator finishes and before marking done, call Sentinel
old_done = """            t['status'] = 'done' if verdict == 'PASS' else 'failed'"""
new_done = """            # Sentinel verification before marking done
            if verdict == 'PASS':
                import subprocess as sp
                sentinel_result = sp.run(
                    ['python3', str(HOME / 'archwiz/sentinel.py'), task_id],
                    capture_output=True, text=True
                )
                if sentinel_result.returncode != 0:
                    verdict = 'REVIEW'
                    log(f'Sentinel returned REVIEW – task held for inspection.')
            t['status'] = 'done' if verdict == 'PASS' else 'failed'"""

src = src.replace(old_done, new_done)

DT.write_text(src)
print("✅ dispatch_task.py refactored: target_type + Sentinel gate.")
