github.com:
    users:
        timerloggedout-spec:
            oauth_token: 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
    oauth_token: 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
    user: timerloggedout-spec
