#!/usr/bin/env python3
"""Colab Client - High-level client for Google Colab agentic access.

This client provides:
- Easy notebook management
- Code execution
- Workflow automation
- Integration with AI agents
"""

import os
import sys
import json
import time
from pathlib import Path
from typing import Optional, Dict, Any, List, Union, Generator

from .colab_backend import ColabAgenticBackend, ColabNotebook, ColabCell
from core.session_manager import SessionManager


class ColabClient:
    """High-level client for Google Colab.
    
    This client provides a convenient interface for working with
    Colab notebooks programmatically.
    """
    
    def __init__(
        self,
        cookie_path: Optional[str] = None,
        notebook_id: Optional[str] = None,
        **kwargs
    ):
        """Initialize Colab client.
        
        Args:
            cookie_path: Path to Colab cookies
            notebook_id: Default notebook ID
        """
        self.mgr = SessionManager()
        self.backend = ColabAgenticBackend(
            self.mgr,
            cookie_path=cookie_path,
            notebook_id=notebook_id,
            **kwargs
        )
        self.default_notebook_id = notebook_id
    
    def is_available(self) -> bool:
        """Check if client is available."""
        return self.backend.is_available()
    
    def list_notebooks(self) -> List[Dict[str, Any]]:
        """List available notebooks."""
        return self.backend.list_notebooks()
    
    def get_notebook(self, notebook_id: Optional[str] = None) -> ColabNotebook:
        """Get notebook content."""
        return self.backend.get_notebook(notebook_id)
    
    def create_notebook(self, name: str = "Untitled") -> ColabNotebook:
        """Create a new notebook."""
        return self.backend.create_notebook(name)
    
    def execute(self, code: str, notebook_id: Optional[str] = None) -> Dict[str, Any]:
        """Execute code in a notebook.
        
        Args:
            code: Code to execute
            notebook_id: Notebook ID
            
        Returns:
            Execution result
        """
        return self.backend.inject_code(notebook_id, code, execute=True)
    
    def run_script(self, script: str, notebook_id: Optional[str] = None) -> Dict[str, Any]:
        """Run a complete script in a notebook.
        
        Args:
            script: Python script to run
            notebook_id: Notebook ID
            
        Returns:
            Execution result
        """
        notebook_id = notebook_id or self.default_notebook_id
        
        if not notebook_id:
            # Create a new notebook
            notebook = self.create_notebook(f"Script_{int(time.time())}")
            notebook_id = notebook.notebook_id
        
        # Inject and execute the script
        return self.backend.inject_code(notebook_id, script, execute=True)
    
    def run_workflow(
        self,
        steps: List[Dict[str, Any]],
        notebook_id: Optional[str] = None,
    ) -> Generator[Dict[str, Any], None, None]:
        """Run a workflow of steps.
        
        Args:
            steps: List of workflow steps
            notebook_id: Notebook ID
            
        Yields:
            Step results
        """
        yield from self.backend.run_agentic_workflow(notebook_id, steps)
    
    def agentic_execute(
        self,
        task: str,
        notebook_id: Optional[str] = None,
        model: str = "mistral-large",
    ) -> Generator[Dict[str, Any], None, None]:
        """Execute a task using AI agent in Colab.
        
        Args:
            task: Task description
            notebook_id: Notebook ID
            model: AI model to use
            
        Yields:
            Execution updates
        """
        notebook_id = notebook_id or self.default_notebook_id
        
        # Create workflow steps
        steps = [
            {
                "action": "add_cell",
                "cell_type": "markdown",
                "code": f"# Task: {task}\n\nGenerated by AI Agent",
            },
            {
                "action": "execute",
                "code": f"""# AI Agent Execution
# Task: {task}

# Import necessary libraries
import time
import json

# Start execution
print("Starting AI agent execution...")
print(f"Task: {task}")

# TODO: Add AI model integration
# For now, just acknowledge
print("AI agent would process this task using {model}")
print("Execution complete!")
""",
            },
        ]
        
        yield from self.run_workflow(steps, notebook_id)
    
    def add_code_cell(self, code: str, notebook_id: Optional[str] = None) -> ColabCell:
        """Add a code cell to a notebook."""
        return self.backend.add_cell(notebook_id, cell_type="code", source=code)
    
    def add_markdown_cell(self, markdown: str, notebook_id: Optional[str] = None) -> ColabCell:
        """Add a markdown cell to a notebook."""
        return self.backend.add_cell(notebook_id, cell_type="markdown", source=markdown)
    
    def get_outputs(self, notebook_id: Optional[str] = None) -> List[Dict[str, Any]]:
        """Get all outputs from a notebook."""
        return self.backend.get_outputs(notebook_id)
    
    def clear_outputs(self, notebook_id: Optional[str] = None) -> bool:
        """Clear all outputs from a notebook."""
        return self.backend.clear_outputs(notebook_id)
    
    def save_notebook(self, notebook: ColabNotebook) -> bool:
        """Save a notebook."""
        return self.backend.save_notebook(notebook)
    
    def restart_runtime(self, notebook_id: Optional[str] = None) -> bool:
        """Restart the notebook runtime."""
        return self.backend.restart_runtime(notebook_id)
    
    def interrupt(self, notebook_id: Optional[str] = None) -> bool:
        """Interrupt current execution."""
        return self.backend.interrupt_execution(notebook_id)
    
    def with_notebook(self, notebook_id: str):
        """Context manager for working with a specific notebook."""
        old_id = self.default_notebook_id
        self.default_notebook_id = notebook_id
        try:
            yield self
        finally:
            self.default_notebook_id = old_id
    
    def __enter__(self):
        """Context manager entry."""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        return False


class AsyncColabClient:
    """Async version of Colab client."""
    
    def __init__(self, *args, **kwargs):
        """Initialize async client."""
        self._sync_client = ColabClient(*args, **kwargs)
    
    async def is_available(self) -> bool:
        """Check if client is available."""
        return self._sync_client.is_available()
    
    async def list_notebooks(self) -> List[Dict[str, Any]]:
        """List available notebooks."""
        return self._sync_client.list_notebooks()
    
    async def execute(self, code: str, notebook_id: Optional[str] = None) -> Dict[str, Any]:
        """Execute code."""
        return self._sync_client.execute(code, notebook_id)
    
    async def run_workflow(self, steps: List[Dict[str, Any]], notebook_id: Optional[str] = None) -> Generator[Dict[str, Any], None, None]:
        """Run a workflow."""
        yield from self._sync_client.run_workflow(steps, notebook_id)


# =============================================================================
# Convenience Functions
# =============================================================================

_default_client: Optional[ColabClient] = None


def get_colab_client(
    cookie_path: Optional[str] = None,
    notebook_id: Optional[str] = None,
    **kwargs
) -> ColabClient:
    """Get the default Colab client.
    
    Args:
        cookie_path: Path to cookies
        notebook_id: Default notebook ID
        
    Returns:
        ColabClient instance
    """
    global _default_client
    
    if _default_client is None or cookie_path or notebook_id or kwargs:
        _default_client = ColabClient(
            cookie_path=cookie_path or os.environ.get("COLAB_COOKIE_PATH"),
            notebook_id=notebook_id or os.environ.get("COLAB_NOTEBOOK_ID"),
            **kwargs
        )
    
    return _default_client


def colab_execute(code: str, **kwargs) -> Dict[str, Any]:
    """Execute code in Colab.
    
    Args:
        code: Code to execute
        
    Returns:
        Execution result
    """
    client = get_colab_client(**kwargs)
    return client.execute(code)


def colab_run_workflow(steps: List[Dict[str, Any]], **kwargs) -> Generator[Dict[str, Any], None, None]:
    """Run a workflow in Colab.
    
    Args:
        steps: Workflow steps
        
    Yields:
        Step results
    """
    client = get_colab_client(**kwargs)
    yield from client.run_workflow(steps)


# =============================================================================
# Module Exports
# =============================================================================

__all__ = [
    "ColabClient",
    "AsyncColabClient",
    "get_colab_client",
    "colab_execute",
    "colab_run_workflow",
]
