#!/usr/bin/env python3
"""Multi-category GitHub repo tagging for timerloggedout-spec.

Harvest plane (owned + starred + optional observatory merge). Applies deterministic
multi-label tags and writes autogenerated artifacts under
docs/ops/generated/github-tagging/.

KEEP SEPARATE from repository-observatory (index/provenance) and lane-matrix-sweep
(PR disposition board). Integrative hooks only: optional observatory JSON merge,
harvest matrix (priority × domain), visibility board for dashboards.

GitHub metadata = fact layer. Tags = deterministic inference (rule engine).
JSON is canonical; Markdown/CSV are projections.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

API = "https://api.github.com"
UA = "termux-monorepo-github-tagging/1.1"
SCHEMA_VERSION = "2.1.0"
MAX_PAGES = 100
RETRIES = 3

RULES: list[tuple[list[str], dict[str, Any]]] = [
    (["termux-monorepo"], {"relationship": "own", "type": ["monorepo"], "domain": ["agentic-ops", "github-automation"], "intent": "keep-active", "priority": "P0"}),
    (["termux-mcp", "android-mcp"], {"relationship": "own", "type": ["mcp-server"], "domain": ["mcp", "termux-android"], "intent": "keep-active", "priority": "P0"}),
    (["mcp-multi-host"], {"relationship": "own", "type": ["mcp-catalog"], "domain": ["mcp"], "intent": "archive-candidate", "priority": "P2"}),
    (["timerloggedout-spec.github.io"], {"relationship": "own", "type": ["marketing", "docs-site"], "domain": ["devex"], "intent": "keep-active", "priority": "P1"}),
    (["gh-aw_fork", "gh-aw-mcpg"], {"relationship": "fork", "type": ["github-automation", "mcp-gateway"], "domain": ["github-automation", "mcp"], "intent": "keep-active", "priority": "P0"}),
    (["gh-mcp", "gh_mcp_server", "agentix"], {"relationship": "seeded", "type": ["mcp-server"], "domain": ["mcp", "github-automation"], "intent": "track-upstream", "priority": "P1"}),
    (["hermes", "kilocode", "lazycodex", "superpowers", "openclaw", "opencode", "cline", "codex", "crush", "oh-my-pi", "wingman", "merl", "bmad", "orkas", "paperclip", "agentos", "agentic-path", "mistral-vibe"],
     {"type": ["coding-agent", "agent-harness"], "domain": ["agentic-ops"], "intent": "track-upstream", "priority": "P1"}),
    (["metatron", "context-md", "eidetic", "memory", "synapse", "pyrite", "cost-of-remembering", "multi-ide-memory"],
     {"type": ["agent-memory"], "domain": ["memory-context"], "intent": "extract-pattern", "priority": "P1"}),
    (["skill", "skillopt", "superpowers", "skills_fork"],
     {"type": ["agent-skills"], "domain": ["skills"], "intent": "extract-pattern", "priority": "P1"}),
    (["mcp"],
     {"type": ["mcp-server"], "domain": ["mcp"], "intent": "track-upstream", "priority": "P1"}),
    (["law", "legal", "catala", "dfir", "statedecode", "statedb", "forensic", "statute", "redamon", "offensive"],
     {"type": ["legal-dfir", "security-offensive"], "domain": ["legaltech", "dfir", "security"], "intent": "keep-active", "priority": "P1"}),
    (["anki", "fsrs", "srs"],
     {"type": ["anki-srs"], "domain": ["srs-learning"], "intent": "keep-active", "priority": "P1"}),
    (["obsidian"],
     {"type": ["obsidian", "knowledge-mgmt"], "domain": ["knowledge-graph"], "intent": "keep-active", "priority": "P1"}),
    (["termux", "shizuku", "haven", "thor", "ankiconnectandroid", "reappzuku"],
     {"type": ["mobile-android", "termux"], "domain": ["termux-android"], "intent": "track-upstream", "priority": "P1"}),
    (["bifrost", "omniroute", "router", "openrouter"],
     {"type": ["library"], "domain": ["llm-routing"], "intent": "integration-pin", "priority": "P0"}),
    (["gantt", "planning", "taiga", "camshaft", "montt"],
     {"type": ["cli-tool"], "domain": ["agentic-ops"], "intent": "extract-pattern", "priority": "P2"}),
    (["atlas", "mobius", "alphadesk", "quant", "trading"],
     {"type": ["quant-trading"], "domain": ["quant"], "intent": "experiment", "priority": "P2"}),
    (["awesome-", "fucking-awesome"],
     {"type": ["awesome-list"], "domain": ["research-papers"], "intent": "reference-only", "priority": "P3"}),
    (["terraform", "ona-runner", "runner_fork"],
     {"type": ["infra-iac"], "domain": ["infra"], "intent": "reference-only", "priority": "P3"}),
    (["xterm", "tabby", "frankenterm", "frankentui", "waveterm"],
     {"type": ["tui"], "domain": ["ui-terminal"], "intent": "track-upstream", "priority": "P2"}),
    (["sail-cli", "autoship", "deploy"],
     {"type": ["deploy"], "domain": ["infra"], "intent": "help-wanted-neighbor", "priority": "P2"}),
    (["jules"],
     {"type": ["coding-agent"], "domain": ["agentic-ops", "github-automation"], "intent": "track-upstream", "priority": "P1"}),
    (["lean", "mathlib", "aesop"],
     {"type": ["research"], "domain": ["research-papers"], "intent": "extract-pattern", "priority": "P2"}),
]

OWN_NAMES = frozenset({
    "termux-monorepo", "termux-mcp", "android-mcp",
    "timerloggedout-spec.github.io", "mcp-multi-host",
})
SEEDED = frozenset({"agentix_fork", "gh_mcp_server_fork", "gh-mcp_fork"})


def now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def get_json(path: str, token: str, params: dict[str, Any] | None = None) -> Any:
    query = "?" + urllib.parse.urlencode(params or {}) if params else ""
    req = urllib.request.Request(
        API + path + query,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": UA,
        },
    )
    for attempt in range(RETRIES):
        try:
            with urllib.request.urlopen(req, timeout=45) as response:  # nosec B310
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            if exc.code not in {429, 500, 502, 503, 504} or attempt == RETRIES - 1:
                raise
            retry_after = exc.headers.get("Retry-After")
            delay = min(int(retry_after), 60) if retry_after and retry_after.isdigit() else 2**attempt
            time.sleep(delay)
        except (urllib.error.URLError, TimeoutError):
            if attempt == RETRIES - 1:
                raise
            time.sleep(2**attempt)
    raise RuntimeError(f"GitHub API request failed: {path}")


def pages(path: str, token: str, params: dict[str, Any], fetch: Callable[..., Any] = get_json) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for page in range(1, MAX_PAGES + 1):
        payload = fetch(path, token, dict(params, per_page=100, page=page))
        if not isinstance(payload, list):
            raise RuntimeError(f"expected list from {path}")
        out.extend(x for x in payload if isinstance(x, dict))
        if len(payload) < 100:
            return out
    raise RuntimeError(f"pagination exceeded {MAX_PAGES} pages for {path}")


def language_family(lang: str | None) -> str:
    l = (lang or "").lower()
    if l == "python":
        return "python"
    if l in ("typescript", "javascript"):
        return "typescript"
    if l == "rust":
        return "rust"
    if l == "go":
        return "go"
    if l in ("kotlin", "java"):
        return "kotlin-java"
    if l in ("shell", "bash"):
        return "shell"
    if l == "ocaml":
        return "ocaml"
    return "unknown"


def tag_repo(name: str, description: str, language: str | None, is_fork: bool, archived: bool) -> dict[str, Any]:
    blob = f"{name} {description or ''}".lower()
    tags: dict[str, Any] = {
        "relationship": "fork" if is_fork or "_fork" in name else "own",
        "type": [],
        "domain": [],
        "intent": "track-upstream",
        "language_family": language_family(language),
        "priority": "P2",
    }
    if archived:
        tags["intent"] = "archive-candidate"
        tags["priority"] = "P3"
    for keys, assign in RULES:
        if any(k.lower() in blob for k in keys):
            for k, v in assign.items():
                if k in ("type", "domain") and isinstance(v, list):
                    for x in v:
                        if x not in tags[k]:
                            tags[k].append(x)
                else:
                    tags[k] = v
    if not tags["type"]:
        tags["type"] = ["other"]
    if not tags["domain"]:
        tags["domain"] = ["devex"]
    if name in OWN_NAMES:
        tags["relationship"] = "own"
    if name in SEEDED:
        tags["relationship"] = "seeded"
    if name == "termux-monorepo-sparked":
        tags["relationship"] = "sparked-redirect"
        tags["intent"] = "archive-candidate"
        tags["priority"] = "P3"
    return tags


def normalize_owned(repo: dict[str, Any]) -> dict[str, Any]:
    name = repo.get("name") or ""
    tags = tag_repo(name, repo.get("description") or "", repo.get("language"), bool(repo.get("fork")), bool(repo.get("archived")))
    flat = sorted(set(tags["type"] + tags["domain"] + [tags["relationship"], tags["intent"], tags["priority"], tags["language_family"]]))
    parent = repo.get("parent") or {}
    return {
        "name": name, "full_name": repo.get("full_name"), "html_url": repo.get("html_url"),
        "description": repo.get("description") or "", "language": repo.get("language"),
        "fork": bool(repo.get("fork")), "archived": bool(repo.get("archived")),
        "stargazers_count": repo.get("stargazers_count") or 0,
        "updated_at": repo.get("updated_at") or "", "created_at": repo.get("created_at") or "",
        "upstream": parent.get("full_name") or "", "provenance": ["owned"], **tags, "tags_flat": "|".join(flat),
    }


def normalize_starred(repo: dict[str, Any]) -> dict[str, Any]:
    name = repo.get("name") or ""
    tags = tag_repo(name, repo.get("description") or "", repo.get("language"), bool(repo.get("fork")), bool(repo.get("archived")))
    if tags["intent"] == "track-upstream" and tags["priority"] == "P2":
        tags["intent"] = "reference-only"
    flat = sorted(set(tags["type"] + tags["domain"] + [tags["relationship"], tags["intent"], tags["priority"], tags["language_family"]]))
    return {
        "name": name, "full_name": repo.get("full_name"), "html_url": repo.get("html_url"),
        "description": repo.get("description") or "", "language": repo.get("language"),
        "fork": bool(repo.get("fork")), "archived": bool(repo.get("archived")),
        "stargazers_count": repo.get("stargazers_count") or 0, "updated_at": repo.get("updated_at") or "",
        "provenance": ["starred"], **tags, "tags_flat": "|".join(flat),
    }


def taxonomy() -> dict[str, Any]:
    return {
        "version": SCHEMA_VERSION, "builder": "termux-monorepo.github_tagging@1.1",
        "dimensions": {
            "relationship": ["own", "fork", "seeded", "sparked-redirect", "mirror"],
            "type": ["coding-agent", "agent-harness", "agent-memory", "agent-skills", "mcp-server", "mcp-gateway", "mcp-catalog", "cli-tool", "tui", "legal-dfir", "security-offensive", "anki-srs", "obsidian", "knowledge-mgmt", "mobile-android", "termux", "quant-trading", "awesome-list", "infra-iac", "deploy", "library", "monorepo", "marketing", "docs-site", "research", "browser", "other"],
            "domain": ["agentic-ops", "llm-routing", "memory-context", "skills", "mcp", "github-automation", "termux-android", "legaltech", "dfir", "srs-learning", "knowledge-graph", "quant", "devex", "security", "infra", "research-papers", "ui-terminal"],
            "intent": ["keep-active", "track-upstream", "extract-pattern", "help-wanted-neighbor", "reference-only", "archive-candidate", "integration-pin", "experiment"],
            "priority": ["P0", "P1", "P2", "P3"],
        },
        "filter_dsl": ["domain:mcp AND intent:keep-active", "type:coding-agent OR type:agent-harness", "relationship:fork AND domain:legaltech", "priority:P0 AND NOT archived:true"],
        "related_lanes": {
            "repository-observatory": "index + provenance (KEEP SEPARATE)",
            "lane-matrix-sweep": "PR disposition board (KEEP SEPARATE)",
            "github-tagging-refresh": "multi-label filter harvest (this lane)",
            "integration": "hooks only — harvest_matrix + visibility board + optional observatory merge",
        },
    }


def snapshot_hash(payload: dict[str, Any]) -> str:
    body = {k: v for k, v in payload.items() if k not in ("generated_at", "snapshot_hash")}
    return hashlib.sha256(json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")).hexdigest()


def build_harvest_matrix(repos: list[dict[str, Any]]) -> dict[str, Any]:
    cells: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for rec in repos:
        pri = rec.get("priority") or "P?"
        for d in rec.get("domain") or ["devex"]:
            cells[pri][d] += 1
    matrix = {p: dict(sorted(domains.items(), key=lambda x: -x[1])) for p, domains in sorted(cells.items())}
    return {"axes": {"row": "priority", "col": "domain"}, "cells": matrix, "p0_domains": matrix.get("P0", {}), "p1_domains": matrix.get("P1", {})}


def build_visibility_board(export: dict[str, Any]) -> dict[str, Any]:
    repos = export.get("repos") or []
    return {
        "schema": "github-tagging-visibility/v1",
        "generated_at": export.get("generated_at"),
        "snapshot_hash": export.get("snapshot_hash"),
        "repos_indexed": export.get("repos_indexed"),
        "stars_indexed": export.get("stars_indexed"),
        "p0": [r["name"] for r in repos if r.get("priority") == "P0"],
        "keep_active": [r["name"] for r in repos if r.get("intent") == "keep-active"],
        "harvest_matrix": export.get("harvest_matrix"),
        "stats": export.get("stats"),
        "links": {
            "canonical_json": "docs/ops/generated/github-tagging/repos_tagged.json",
            "csv": "docs/ops/generated/github-tagging/repos_tagged.csv",
            "summary_md": "docs/ops/generated/github-tagging/TAGGING-SUMMARY.md",
            "ops_ssot": "docs/ops/GITHUB-TAGGING-SYSTEM.md",
            "lane_matrix_board": "docs/ops/generated/lane-matrix-status.md",
            "observatory_index": "workspace/llm_map/repositories/repository-index.json",
        },
    }


def maybe_merge_observatory(repos: list[dict[str, Any]], observatory_path: Path | None) -> list[dict[str, Any]]:
    if not observatory_path or not observatory_path.exists():
        return repos
    try:
        data = json.loads(observatory_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return repos
    by_name = {r.get("full_name"): r for r in repos if r.get("full_name")}
    for rec in data.get("repositories") or []:
        fn = rec.get("full_name")
        if not fn or fn not in by_name:
            continue
        by_name[fn]["observatory_provenance"] = rec.get("provenance") or []
        by_name[fn]["observatory_domains"] = (rec.get("classification") or {}).get("domains") or []
    return list(by_name.values()) if by_name else repos


def write_csv(path: Path, records: list[dict[str, Any]]) -> None:
    fields = ["name", "full_name", "html_url", "relationship", "priority", "intent", "language_family", "type", "domain", "tags_flat", "fork", "archived", "language", "description", "updated_at", "upstream", "provenance"]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for rec in records:
            row = dict(rec)
            row["type"] = "|".join(rec.get("type") or [])
            row["domain"] = "|".join(rec.get("domain") or [])
            row["provenance"] = "|".join(rec.get("provenance") or [])
            w.writerow(row)


def write_summary_md(path: Path, export: dict[str, Any]) -> None:
    repos = export.get("repos") or []
    p0 = [r for r in repos if r.get("priority") == "P0"]
    keep = [r for r in repos if r.get("intent") == "keep-active"]
    matrix = export.get("harvest_matrix") or {}
    lines = ["# GitHub multi-category tagging (generated)", "", f"Generated: `{export.get('generated_at')}`", f"Snapshot: `{export.get('snapshot_hash', '')[:12]}`", f"Owned indexed: **{export.get('repos_indexed', 0)}** · Stars sample: **{export.get('stars_indexed', 0)}**", "", "## Stats", "", f"- Priority: `{export.get('stats', {}).get('by_priority')}`", f"- Intent: `{export.get('stats', {}).get('by_intent')}`", f"- Top domains: `{export.get('stats', {}).get('by_domain_top')}`", "", "## Harvest matrix (priority × domain)", "", "```json", json.dumps(matrix.get("cells") or {}, indent=2)[:4000], "```", "", "## P0", ""]
    for r in p0:
        lines.append(f"- **{r['name']}** — {', '.join(r.get('type') or [])} · {r.get('intent')} · {', '.join(r.get('domain') or [])}")
    lines.extend(["", "## Keep-active", ""])
    for r in keep:
        lines.append(f"- `{r['name']}` — {r.get('priority')} · {', '.join((r.get('type') or [])[:3])}")
    lines.extend(["", "## Related boards (KEEP SEPARATE)", "", "- Lane matrix: `docs/ops/generated/lane-matrix-status.md`", "- Observatory index: `workspace/llm_map/repositories/repository-index.json`", "- This filter surface: `docs/ops/generated/github-tagging/`", "", "> Autogenerated by `scripts/github/github_tagging.py` via `github-tagging-refresh`.", "> Do not hand-edit; change rules in the script and let cron regenerate.", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def build_export(owned_raw: list[dict[str, Any]], starred_raw: list[dict[str, Any]], owner: str) -> dict[str, Any]:
    repos = [normalize_owned(r) for r in owned_raw if (r.get("owner") or {}).get("login") == owner or r.get("full_name", "").startswith(f"{owner}/")]
    if not repos:
        repos = [normalize_owned(r) for r in owned_raw]
    stars = [normalize_starred(r) for r in starred_raw]
    by_priority: dict[str, int] = defaultdict(int)
    by_intent: dict[str, int] = defaultdict(int)
    by_domain: dict[str, int] = defaultdict(int)
    for rec in repos:
        by_priority[rec["priority"]] += 1
        by_intent[rec["intent"]] += 1
        for d in rec["domain"]:
            by_domain[d] += 1
    export: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION, "builder": "termux-monorepo.github_tagging@1.1", "account": owner,
        "generated_at": now(), "repos_indexed": len(repos), "stars_indexed": len(stars),
        "stats": {"by_priority": dict(sorted(by_priority.items())), "by_intent": dict(sorted(by_intent.items(), key=lambda x: -x[1])), "by_domain_top": dict(sorted(by_domain.items(), key=lambda x: -x[1])[:20])},
        "harvest_matrix": build_harvest_matrix(repos), "taxonomy": taxonomy(),
        "repos": sorted(repos, key=lambda r: (r.get("priority") or "P9", r.get("name") or "")),
        "stars_sample": stars[:200],
    }
    export["snapshot_hash"] = snapshot_hash(export)
    return export


def main(argv: list[str] | None = None, fetch: Callable[..., Any] = get_json) -> int:
    parser = argparse.ArgumentParser(description="Multi-category GitHub tagging (autogenerated artifacts)")
    parser.add_argument("--owner", required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("docs/ops/generated/github-tagging"))
    parser.add_argument("--token-env", default="GITHUB_TAGGING_TOKEN")
    parser.add_argument("--max-star-pages", type=int, default=8)
    parser.add_argument("--observatory-index", type=Path, default=Path("workspace/llm_map/repositories/repository-index.json"))
    args = parser.parse_args(argv)
    token = os.environ.get(args.token_env) or os.environ.get("GITHUB_TOKEN") or os.environ.get("REPOSITORY_OBSERVATORY_TOKEN")
    if not token:
        print(f"missing {args.token_env} or GITHUB_TOKEN", file=sys.stderr)
        return 2
    me = fetch("/user", token)
    login = me.get("login") if isinstance(me, dict) else None
    if login != args.owner:
        raise RuntimeError(f"authenticated GitHub user is {login!r}, expected {args.owner!r}")
    owned = pages("/user/repos", token, {"affiliation": "owner", "sort": "updated", "direction": "desc"}, fetch=fetch)
    starred: list[dict[str, Any]] = []
    for page in range(1, args.max_star_pages + 1):
        payload = fetch("/user/starred", token, {"sort": "updated", "direction": "desc", "per_page": 100, "page": page})
        if not isinstance(payload, list):
            raise RuntimeError("expected list from /user/starred")
        starred.extend(x for x in payload if isinstance(x, dict))
        if len(payload) < 100:
            break
    export = build_export(owned, starred, args.owner)
    export["repos"] = maybe_merge_observatory(export["repos"], args.observatory_index)
    export["repos_indexed"] = len(export["repos"])
    export["harvest_matrix"] = build_harvest_matrix(export["repos"])
    export["snapshot_hash"] = snapshot_hash(export)
    out = args.out_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "taxonomy.json").write_text(json.dumps(export["taxonomy"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out / "repos_tagged.json").write_text(json.dumps(export, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_csv(out / "repos_tagged.csv", export["repos"])
    write_summary_md(out / "TAGGING-SUMMARY.md", export)
    (out / "stars_tagged_sample.json").write_text(json.dumps({"count": len(export["stars_sample"]), "stars": export["stars_sample"]}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out / "visibility-board.json").write_text(json.dumps(build_visibility_board(export), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out / "harvest-matrix.json").write_text(json.dumps(export["harvest_matrix"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"repos_indexed": export["repos_indexed"], "stars_indexed": export["stars_indexed"], "snapshot_hash": export["snapshot_hash"][:12], "by_priority": export["stats"]["by_priority"], "p0_domains": export["harvest_matrix"].get("p0_domains")}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
