claude:
  cookie_path: ~/.multi-ai-tokens/claude_cookies.json
  token_path: ~/.multi-ai-tokens/claude_token.txt
colab:
  cookie_path: ~/deepseek-cli/cookies_2.json
  notebook_id: default
deepseek:
  cookie_path: ~/deepseek-cli/cookies_2.json
  token_path: ~/deepseek-cli/token_account2.txt
gemini:
  cookie_path: ~/deepseek-cli/cookies_2.json
  token_path: ~/.multi-ai-tokens/gemini_token.txt
mistral:
  cookie_path: ~/.multi-ai-tokens/mistral_cookies.json
  token_path: ~/.multi-ai-tokens/mistral_token.txt
